### ISSUE TITLE
It is not possible to use this repository as a git submodule

### ISSUE THREAD

**Issue by feloy** [kubernetes-sigs/reference-docs#226]
It is not possible to use this repository as a git submodule.

Steps to reproduce:

```
$ mkdir test
$ cd test
$ git init
$ git submodule add https://github.com/kubernetes-sigs/reference-docs.git
$ git submodule update --init --recursive 
fatal: No url found for submodule path 'reference-docs/docsy-example/themes/docsy' in .gitmodules
Failed to recurse into submodule path 'reference-docs'
```

I can see there is a .gitmodules file in the `docsy-example` directory, but I would suggest it should be in the root directory.

**Comment by kbhawkey** [comment]
Yes, the addition of the docsy example repo was merged prematurely. It does work as expected.
I need to remove the "inner" repo and look into adding the example sub-tree in a different way.
I think the repository could use a minimal "docsy" file structure and theme sub-module so that we
can test the rendered reference pages. We don't need the entire example repository.

**Comment by kbhawkey** [comment]
Temporarily assigning myself.

/assign
